### ISSUE TITLE
SuppressionList does not display records when viewing lists

### ISSUE THREAD

**Issue by kcaponeAP** [activeprospect/leadconduit-integration-suppressionlist#29] opened 2015-06-05 20:30 UTC
When you view a list created in SL, you have to click through the 'Upload Records' button to see if the list contains any records and to access the list URLs, etc.

Steps to reproduce:

1. Create a list in SL by using the + button at the bottom. Give it a name, etc. Save.
2. Go do something else, like go into LCN or something.
3. Go back into SL and view the list you created. Where is the number of entries?

You have to click through to get to the information needed:

1. Click upload records (even though you aren't uploading any)
2. At the Upload a file screen, click done.

Only now can you view information related to the list. Please fix so that you can see the list information when it is selected in the list on the right.

![omittedinfo](https://cloud.githubusercontent.com/assets/8238417/8014611/d226ce86-0b97-11e5-98eb-648b36e3badd.png)

**Comment by cgrayson** [comment] 2015-06-05 20:32
Duplicate of [SuppressionList issue #54](https://github.com/activeprospect/suppressionlist/issues/54).

**Comment by kcaponeAP** [comment] 2015-06-05 20:33
@cgrayson Perhaps. though, this is the behavior when the list is populated as well. Same issue?

**Closed by cgrayson** 2015-06-05 20:32 UTC
Labels: enhancement

**Comment by cgrayson** [comment] 2015-06-05 20:37
Not exactly, true. But I think [#53](https://github.com/activeprospect/suppressionlist/issues/53) covers the difference.
